---
apiVersion: v1
kind: Pod
metadata:
    name: platform-core-api
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 4
          memory: 8Gi 
        requests:
          cpu: 3
          memory: 6Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-data-api
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 4
          memory: 8Gi 
        requests:
          cpu: 2
          memory: 4Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-object-api
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 4
          memory: 8Gi 
        requests:
          cpu: 4
          memory: 8Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true


---
apiVersion: v1
kind: Pod
metadata:
    name: platform-core-api-kafka
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 1
          memory: 1Gi 
        requests:
          cpu: 1
          memory: 1Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-core-api-kafka-zookeeper
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 0.25
          memory: 256Mi 
        requests:
          cpu: 0.25
          memory: 256Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true


---
apiVersion: v1
kind: Pod
metadata:
    name: platform-data-api-kafka
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 1
          memory: 1Gi 
        requests:
          cpu: 1
          memory: 1Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-data-api-kafka-zookeeper
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 0.25
          memory: 256Mi 
        requests:
          cpu: 0.25
          memory: 256Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-object-api-kafka
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 1
          memory: 1Gi 
        requests:
          cpu: 1
          memory: 1Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true


---
apiVersion: v1
kind: Pod
metadata:
    name: platform-object-api-kafka-zookeeper
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 0.25
          memory: 256Mi 
        requests:
          cpu: 0.25
          memory: 256Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true


---
apiVersion: v1
kind: Pod
metadata:
    name: platform-core-api-mongodb
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 2
          memory: 4Gi 
        requests:
          cpu: 2
          memory: 4Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-data-api-mongodb
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 2
          memory: 4Gi 
        requests:
          cpu: 2
          memory: 4Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-object-api-mongodb
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 6
          memory: 12Gi 
        requests:
          cpu: 6
          memory: 12Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true


---
apiVersion: v1
kind: Pod
metadata:
    name: platform-object-api-postgres
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 4
          memory: 8Gi 
        requests:
          cpu: 4
          memory: 8Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-data-api-postgres
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 2
          memory: 2.5Gi 
        requests:
          cpu: 2
          memory: 2.5Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true


---
apiVersion: v1
kind: Pod
metadata:
    name: redis-master
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 6
          memory: 12Gi 
        requests:
          cpu: 4
          memory: 8Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: redis-replica
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 3
          memory: 6Gi 
        requests:
          cpu: 3
          memory: 6Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: keycloak
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 2
          memory: 4Gi 
        requests:
          cpu: 2
          memory: 4Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true


# ---
# apiVersion: v1
# kind: Pod
# metadata:
#     name: higher
#     namespace: default
# spec:
#   containers:
#     - name: pause
#       image: k8s.gcr.io/pause:3.5
#       resources:
#         limits:
#           cpu: 2
#           memory: 2.5Gi 
#         requests:
#           cpu: 2
#           memory: 2.5Gi
#       terminationMessagePath: /dev/termination-log
#       terminationMessagePolicy: File
#       imagePullPolicy: IfNotPresent
#   tolerations:
#   - key: "env"
#     operator: "Equal"
#     value: "higher"
#     effect: "NoSchedule"
#   restartPolicy: Always
#   terminationGracePeriodSeconds: 30
#   dnsPolicy: ClusterFirst
#   securityContext: {}
#   enableServiceLinks: true


---
apiVersion: v1
kind: Pod
metadata:
    name: platform-core-api-r1
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 3
          memory: 6Gi 
        requests:
          cpu: 3
          memory: 6Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-data-api-r1
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 4
          memory: 8Gi 
        requests:
          cpu: 2
          memory: 4Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-object-api-r1
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 4
          memory: 8Gi 
        requests:
          cpu: 4
          memory: 8Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-core-api-r2
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 4
          memory: 8Gi 
        requests:
          cpu: 3
          memory: 6Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-data-api-r2
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 4
          memory: 8Gi 
        requests:
          cpu: 2
          memory: 4Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-object-api-r2
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 4
          memory: 8Gi 
        requests:
          cpu: 4
          memory: 8Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true

---
apiVersion: v1
kind: Pod
metadata:
    name: platform-object-api-r3
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 4
          memory: 8Gi 
        requests:
          cpu: 4
          memory: 8Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true


---
apiVersion: v1
kind: Pod
metadata:
    name: platform-object-api-r4
    namespace: default
spec:
  containers:
    - name: pause
      image: k8s.gcr.io/pause:3.5
      resources:
        limits:
          cpu: 4
          memory: 8Gi 
        requests:
          cpu: 4
          memory: 8Gi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  securityContext: {}
  enableServiceLinks: true


